version: '3'
services:
  nginx:
    image: nginx:latest
    env_file:
      - .env
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${APP_DIRECTORY}:/code
      - ./my_vhost.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    build: ./php
    env_file:
      - .env
    volumes:
      - ${APP_DIRECTORY}:/code
  db:
    image: mariadb:10.1
    env_file:
      - .env
    environment:
      TZ: ${MYSQL_TIME_ZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./database:/var/lib/mysql